[workspace]

members = [
    "hello",
    "day1-ex1",
    "day1-ex2",
    "day1-ex3",
    "day1-ex4",
    "day2-ex1",
    "day2-ex2",
    "day2-ex3",
    "day2-ex4",
    "day3-ex1",
    "concurrency-ex1",
    "concurrency-ex2",
    "concurrency-ex3",
    "concurrency-ex4",
    "mini-redis",
]
